output_dir: 'test'

k: 15
ba_threshold: 0.638
population: ['World'] # must be a list of strings
instance_start_size: 'all' # used for benchmarking; start size from where instance is iteratively increased
logging: True
approach: 'hog' # choose either hog or og
min_hits: 1 # choose min number of hits for an allele / haplotype to be covered

peptides: '../OptiVax_Data/Peptides/30_filtered_mhc_peptides.pep'
frequency_data: '../OptiVax_Data/Frequencies/IEDB_population_frequency2392_normalized.pkl'
binding_affinities: '../OptiVax_Data/BindingAffinities/25June_mhc1_netmhc-4.1_pred_affinity_pivot.pkl.gz'
# optional: if use embedded peptides add non-embedded peptides here
# embedded length is either an int value
embedding_length: 0
# unembedded is either the path to the unembedded peptides or False
unembedded: False
# this is either a path to the embedded epitope features or an empty string ''
embedded_epitope_features: ''
